apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "kube-state-metricsfullname" . }}-service-test-metrics"
  labels:
    app: {{ template "kube-state-metricsfullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: ['curl']
      args: ['http://{{ template "kube-state-metrics.fullname" . }}:{{ .Values.service.port }}/metrics']
  restartPolicy: Never