apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "kube-state-metrics.fullname" . }}-service-test-metrics"
  labels:
    app: {{ template "kube-state-metrics.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: metrics-endpoint-test
      image: gcr.io/kubernetes-charts-ci/chart-testing:v1.0.5     
      command: ["sh","-c", "curl http://{{ template "kube-state-metrics.fullname" . }}:{{ .Values.service.port }}/metrics"]
  restartPolicy: Never