apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "fullname" . }}-service-telegrafdb-test"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: ['curl']
      args:  ['http://data-influxdb.kube-system:8086/query?q=select+*+from+telegraf..cpu']
  restartPolicy: Never